title: Azuch's Blog
author: Azuch
email: namlucius@gmail.com
description: "Azuch's Blog"

# beautiful-jekyll specific settings
# We can add more options later from the theme's documentation
avatar: /assets/img/azuch.png
navbar-links:
  About: /about/

# Build settings
theme: beautiful-jekyll-theme
plugins:
  - jekyll-feed
