title: Azuch's Blog
author: Azuch
email: namlucius@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Azuch's Blog

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
#  - about.md

# Build settings
theme: minima
plugins:
  - jekyll-feed
